### ISSUE TITLE
How pelias api communicates with PIP API on kubernetes?

### ISSUE THREAD

**Issue by pravink** [pelias/kubernetes#103]
Hey team! 
I am getting 500 error when i looked closely into pelias api pod logs - 

{"level":"info","message":"::ffff:100.96.2.1 - - [20/Sep/2019:05:59:00 +0000] \"GET /v1/reverse?point.lat=51.5081124&point.lon=-0.0759493 HTTP/1.1\" 500 486","label":"api","timestamp":"2019-09-20T05:59:00.091Z"}

---
#### Here's what I did :innocent:

Pelias API are running fine on kubernetes cluster... 
tried to hit http://pelias-api-load-balancer-url:3100/v1/reverse?point.lat=51.5081124&point.lon=-0.0759493

here is snippet of values.yaml

pip:
  enabled: true
  replicas: 1
  host: "http://pelias-pip-service:3102/"
  dockerTag: "latest"
..

I did a curl on pelias api pod - but he gives nothing
curl http://100.71.136.79:3102
while curl on pelias api itself works fine
---

#### Here's what I got :scream_cat:

but received below error 

{"controller":"search","queryType":"reverse","result_count":0,"params":{"size":10,"private":false,"point.lat":51.5081124,"point.lon":-0.0759493,"boundary.circle.lat":51.5081124,"boundary.circle.lon":-0.0759493,"lang":{"name":"English","iso6391":"en","iso6393":"eng","defaulted":false},"querySize":20},"retries":0,"text_length":0,"level":"info","message":"elasticsearch","label":"api","timestamp":"2019-09-20T05:58:51.671Z"}
{"level":"error","message":"elasticsearch error Error: No Living connections","label":"api","timestamp":"2019-09-20T05:58:51.671Z"}
{"level":"info","message":"::ffff:100.96.2.1 - - **[20/Sep/2019:05:58:51 +0000] \"GET /v1/reverse?point.lat=51.5081124&point.lon=-0.0759493 HTTP/1.1\" 500** 486","label":"api","timestamp":"2019-09-20T05:58:51.672Z"}
Elasticsearch WARNING: 2019-09-20T05:59:00Z

---
#### Here's what I was expecting :sparkles:

---

**Comment by orangejulius** [comment]
Hi @pravink,

There's nothing special about the communication between the API and the PIP service, it's plain old HTTP. It looks like your issue here is Elasticsearch related:

```
{"level":"error","message":"elasticsearch error Error: No Living connections","label":"api","timestamp":"2019-09-20T05:58:51.671Z"}
```

Note that calls to the reverse endpoint will generally result in a query to Elasticsearch first, and then the PIP service.
