### ISSUE TITLE
Why using NFS Persistent Volumes for the importers?

### ISSUE THREAD

**Issue by paulopez78** [pelias/kubernetes#109]
Hi Pelias Team,

First of all thanks for creating and mantaining that awesome project.

We are evaluating the possibility to use pelias in production running in GKE cluster, as I'm pretty new to the project I don't understand the need to use NFS Persistent Volumes for running the importers. What I though is that importers were independent so there is no need for sharing data between the different jobs running the import. 
Our idea was to use persistent volumes using the plugin of the cloud provider and not nfs, in that case GCP. Would it be possible?

Regards,
Pau.

**Comment by acondrat** [comment]
We do not share data between importers and use `emptyDir` volumes for all of them, except `whosonfirst`. The latter requires a lot of disk space and inodes so we use a 1000G pd-ssd volume for it.

**Comment by paulopez78** [comment]
Thanks for you quick reply,

I will do exactly what you suggest but this is confusing because latest version of the chart is showing a Persistent Volume (not `emptyDir`) mounted in all the exporters, for example here:

https://github.com/pelias/kubernetes/blob/master/build/templates/openaddresses-import-job.tpl#L63
https://github.com/pelias/kubernetes/blob/master/build/templates/openstreetmap-import-job.tpl#L63

**Comment by acondrat** [comment]
Yes, this is true. We created our own helm chart for because of that.
