### ISSUE TITLE
Templates are using outdated Kubernetes version

### ISSUE THREAD

**Issue by williamflynt** [pelias/kubernetes#111]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
`helm install --name pelias --namespace pelias ./ -f ./values.yaml`

---
#### Here's what I got :scream_cat:
`Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"`

---
#### Here's what I was expecting :sparkles:
Magical geocoding success

---
#### Here's what I think could be improved :trophy:
We should migrate to Kubernetes 1.16, to include updating templates from `extensions/v1beta1` to `apps/v1`  and other structural changes to the templates

**Comment by orangejulius** [comment]
Hi @williamflynt,
I was wondering when someone was going to report this :)

We haven't upgraded to K8S 1.16 yet, but we knew this was coming. At the very least, I think the change from `extensions/v1beta1` to `apps/v1` is pretty backwards compatible. If you'd like to open a PR we would definitely appreciate it.

Let me know if you know of any other changes in the latest K8S versions.

**Comment by williamflynt** [comment]
Julius -

Saw your talk on interpolation. I can confirm Italian addresses aren't always highly documented. Even Google has trouble quite often.

This about as little work as possible to get Pelias to launch via Helm. I haven't conducted testing beyond the initial `install`.

**Comment by orangejulius** [comment]
Fixed in #112 :)
