### ISSUE TITLE
Kubernetes doc out of date

### ISSUE THREAD

**Issue by ursNiemi** [pelias/kubernetes#123]
Hey team! 

Your Kubernetes documentation (https://github.com/pelias/kubernetes/blob/master/README.md)  seems to be out of date:
* Helm installation instructions lead to current Helm version 3, which is incompatible with the sample code in subchapter **Pelias Helm Chart installation**, i.e. `--name` is unknown flag 
* The location where to find Pelias Chart is not explained: 
> ./path/to/pelias/chart 

if it is current directory (https://github.com/pelias/kubernetes), then the current directory is not compatible with Helm 3. 

`helm repo add kubernetes https://github.com/pelias/kubernetes`
leads to 
`Error: looks like "https://github.com/pelias/kubernetes" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/pelias/kubernetes/index.yaml : 404 Not Found`

Or did I understand the instructions wrong somehow?

**Comment by Mokto** [comment]
I'm running Pelias with Helm3 and that works flawlessly ;)

**Comment by deanshelton913** [comment]
Yeah the only diff really is that you need to omit the --name...
Here is a command i am using to install with helm 3:
```sh
helm install pelias --namespace pelias . -f values.yaml -f my-overrides.yaml
```

**Comment by skulos** [comment]
I'm getting a silly error. I downloaded the repo:
<pre>~$ git clone https://github.com/pelias/kubernetes.git
</pre>

Then I changed the directory
<pre>~$ cd kubernetes/
</pre>

And the ran the helm command above:
<pre>~/kubernetes$ helm install pelias --namespace pelias . -f values.yaml
Error: template: pelias/templates/configmap.tpl:34:14: executing &quot;pelias/templates/configmap.tpl&quot; at &lt;(.Values.api.targets.auto_discover) and (or (eq .Values.api.targets.auto_discover true) (eq .Values.api.targets.auto_discover false))&gt;: can&apos;t give argument to non-function .Values.api.targets.auto_discover  
</pre>

(NOTE: I've created a namespace pelias in kubernetes for this deplyment. Am I missing something?)

**Comment by orangejulius** [comment]
Helm 3 support status is now listed in the docs as of https://github.com/pelias/kubernetes/commit/25125b10a9a8dfcab19745305fc22de1cce8d386, so I think this issue is solved (at least in that the docs are up to date, we do want to get around to testing more thoroughly on Helm 3 someday).

@skulos sorry for the administrative noise, but can you please open a new issue to discuss your problem? I susupect the version of `helm` you are using _is_ involved, so can you make sure to share that as well?

Thanks all!
