### ISSUE TITLE
Heap over 31GB

### ISSUE THREAD

**Issue by Binternet** [pelias/kubernetes#33]
As mentioned in `/etc/default/elasticsearch` :
_Heap size defaults to 256m min, 1g max
Set ES_HEAP_SIZE to 50% of available RAM, but no more than 31g_

This is not enforced in
https://github.com/pelias/kubernetes/blob/master/elasticsearch/terraform/templates/user-data.tpl#L50

**Comment by orangejulius** [comment]
Yeah, great idea. We've just been doing the math manually to ensure the heap doesn't go over 31GB. A pull request would be welcome :)

**Comment by Binternet** [comment]
Hope I did it right ;-)

**Comment by orangejulius** [comment]
You did. This is going to save someone a lot of trouble at some point :)

**Comment by Binternet** [comment]
Great, i'm stuck for almost a week with a broken elastic and can't figure out what's wrong ;-/
