### ISSUE TITLE
Is that normal Pelias always download interpolation .gz dbs within init-container ? 

### ISSUE THREAD

**Issue by theobolo** [pelias/kubernetes#39]
Hello guys, 

We are using Pelias at my company but i'm wondering something about the `pelias-interpolation` deployment. Is that normal that the pelias init-container `interpolation-download` is always downloading again and again the `street.db.gz` and the `address.db.gz` from S3 ? 

It costs at lot of ressources and a lot of bandwith just to keep downloading that. As i understand it's the only way you found for the moment to keep street and addresses up to date within the container right ? 

I'm still looking for a more small and cost efficient setup for the interpolation pod, do you have any tips and tricks ?

Kind regards

**Comment by missinglink** [comment]
Hi @theobolo.

I'm trying to think of alternative solutions but they all involve pretty much the same workflow.

For instance, you could bundle the data inside a container, AMI etc but it would still be essentially the same thing, lots of bytes coming across the network on startup.

We generally find that the interpolation service is long-lived and doesn't require restarts very often, so for us this issue isn't so bad.

The solution would probably come in the form of a persistent volume or something similar.

I'm not super familiar with k8s (Julian knows it better), is it possible to create a 'volume', copy the data there once and then mount it read-only from any newly created pods?

**Comment by missinglink** [comment]
Just wanted to add that if the 'volume' workflow I mentioned is possible, there would presumably need to be a mechanism to copy these volumes between nodes, so each node had a copy available when starting new pods.

If the syncing was lazy it would still be slow on the first instantiation and fast thereafter, if the syncing was optimistic, it would potentially require a lot of disk space holding data that was possibly never used?

**Comment by theobolo** [comment]
I think that i found the problem : the Memory Limits are too low, and sometimes the interpolation pod is just killed because it go over 3gb of Ram ... that's why the init-container restart and start to download files again. 

I increased the limits and now the pod is stable, it still Running, no more restarts. On my side i mounted my `/data` volume as explained previously with a PersistentVolume who survives between pod stop and restart. I made a deployment file without the init-container to avoid downloading files even if the pod is stopped and started again, because files are already on the persistentVolume.

I wonder if it should be possible to think about something to automate via the deployment file, downloading or not the two db files... Basically it's possible to just don't use the init-container, and just add a run.sh within the main `pelias/interpolation` image, it could check if the ENV var DOWNLOAD_ASSETS is set to TRUE, if yes then download files, if not, just start the interpolation app without any downloading process ? 

Right now you'r starting interpolation directly from Dockerfile CMD : 

# entrypoint
`CMD [ "./interpolate", "server", "/data/interpolation/address.db", "/data/interpolation/street.db" ]`

We could have just a 
`CMD ["./run.sh"]`

run.sh : 

```
#!/bin/sh

if [ "$ DOWNLOAD_ASSETS" == "true" ]; then
  mkdir -p /data/interpolation/ 
  wget -O- https://s3.amazonaws.com/pelias-data.nextzen.org/interpolation/current/street.db.gz | gunzip > /data/interpolation/street.db 
  wget -O- https://s3.amazonaws.com/pelias-data.nextzen.org/interpolation/current/address.db.gz | gunzip > /data/interpolation/address.db
  echo "Assets Downloaded !"
fi

exec ./interpolate server /data/interpolation/address.db /data/interpolation/street.db
```

witch is doing the check i talked about. I'm suggesting that since for the moment even with a PersistentVolume we have to redownload files at each pod startup, witch should be avoided by my suggestion.

**Comment by theobolo** [comment]
There is also another bug, since you'r not telling to Kubernetes in the CMD of the init-container, the pod in the init-state : 

![image](https://user-images.githubusercontent.com/7281773/43895568-11609d26-9bd6-11e8-864f-cd1a5cda63b4.png)

You just have to modify the deployment file like that : 

```
          command: ["sh", "-c",
            "mkdir -p /data/interpolation/ & \
             wget -O- https://s3.amazonaws.com/pelias-data.nextzen.org/interpolation/current/street.db.gz | gunzip > /data/interpolation/street.db & \
             wget -O- https://s3.amazonaws.com/pelias-data.nextzen.org/interpolation/current/address.db.gz | gunzip > /data/interpolation/address.db"]
```

Result : 

![image](https://user-images.githubusercontent.com/7281773/43897523-90d7166a-9bdc-11e8-972f-53561b3131c9.png)

**Comment by orangejulius** [comment]
Hey @theobolo,
thanks for the report that 3GB of RAM is not enough. I'm really not sue why that would be, considering the init-container is running only `wget` and `gunzip`.

As for the actual storage issue, it's definitely true that managing the ~40GB of disk required for the sqlite DB for the interpolation service is difficult.

There are a couple possibilities that I see, some already mentioned:
- Bundle the data in the container
- Store the data on a persistent volume

Bundling the data in the container _might_ help, but that would also mean kubernetes is storing a huge amount of container data, which it might not always like. With my understanding of k8s, it would only really save disk space if there were several instances of the interpolation service running _per k8s instance_. Currently this isn't generally how we run things, but maybe in the future it would help.

Persistent volumes are initially enticing, but I personally don't see much benefit to them, and in fact a lot of added complexity and problems, in the case where there are multiple replicas of the interpolation service across multiple instances. Except for those lucky folks running on GCE, there aren't many good options for PVs that can have multiple read-clients. So again we run into the issue of storing multiple copies of the data, as well as managing the persistent volume state. The other option is to use NFS (or, in AWS, EFS) to store _one_ copy of the data. EFS in particular has really bad performance characteristics sometimes, so I'm not a fan of using it.

In my mind the most foolproof and simplest solution is still to keep using an emptyDir for the data, and then ensuring a clean slate for each instance of the interpolation service. Let me know if I'm missing something.

**Comment by theobolo** [comment]
@orangejulius Hello :),

So i'll just sum up a little bit my toughts about that, my first problem was : 

 - Why my init-container (who's downloading files) is always restarting after a short period of time and downloads 17Gb of data again and ofc then Gunzip them to the 44gb database ? 

The answer for me was apparently ... the limits witch caused a OOM kill by Kubernetes, but for the moment, i'm not 100% sure about that. What i'm sure about, is that the init-container as the default configuration, is restarting ... and it's not an expected behaviour. Alright

So i wanted to find a solution, because it's not very Prod proof for me to have that kind of bug.
So i talked about my own setup, i'm not using an `init-container` since the previous bug i mentionned is really annoying and costs a lot of bandwith every 10min. I just use a init-script : `run.sh` within the pelias-interpolation image that check if the datas are present or not, it's easier for me because basically i use a Azure SSD persistentVolume mounted on my interpolation pod, so i just need to download data once (when the /data/interpolation directory is missing for exemple). With that when i restart my pod, my init-script see the files (downloaded during a previous startup) and just start the interpolation server without any download and i avoid the init-container restarting problem. If i want to delete datas and start download them again i just have to delete my volume and restart my pod, that's it and it's automatic. 

My main point here is : with the actual configuration, you have 0 control of the downloading process, everytime you restart your pod you have to deal with the init-container downloading files, witch is not always needed and the restart bug witch is not clearly identified. 

Azure / AWS / or GCE have all, as you said, ManyReadWrite storage solutions : AzureFiles, EFS, and don't remember on GCE, basically you'r using that mecanism for the jobs (i'm using a 500gb shared AzureFiles volume for your jobs), and by using the right StorageClass it's basically working well. But for me, pelias-interpolation pod as you mentionned, is a long-term pod and that's why i'm just using PersistentVolume with a PersistentVolumeClaim to bring it to a more Stable setup (witch is not really complex). I don't want to use a ManyReadWrite storage since i just run 1 pelias-interpolation pod. If i wanted to scale my interpolation deployment, i'll just have to use Statefulset with DynamicPersistentVolume claims witch is working also pretty well, ofc i will end with 2 Dbs and data replication on 2 separate volumes, but i'm avoiding poor performances of the shared ManyWriteRead storage solutions.

I understand that you want to keep your deployment files and setup as simple as possible, i was just wondering if you were open to some little improvements :)

The init-container is cool but is not working properly with the basic setup. Maybe adding `restartPolicy: Never` to the init-container should maybe solve the restart issue but still i have 0 control over the downloading process. :)

**Comment by theobolo** [comment]
I found out also that the PIP init-container and the PlaceHolder init-container are also restarting after 10min .... i'll take a look at that too ...

**Comment by theobolo** [comment]
Look at the Pod description, at the bottom we can see that the Init-container as restarted more than 9 times over 3h ... i can't explain why. 

  - I disabled limits
  - I used last CMD syntax
  - I putted a `restartPolicy: Never` on the init-container 

Nothing changed, i will maybe open an issue on the Kubernetes repo ... it's still very strange. 

```
Name:           pelias-placeholder-796f4588d9-dkh26
Namespace:      pelias
Node:           aks-agentpool-46734215-0/10.240.0.4
Start Time:     Fri, 10 Aug 2018 10:05:24 +0000
Labels:         app=pelias-placeholder
                pod-template-hash=3529014485
Annotations:    <none>
Status:         Running
IP:             10.244.2.30
Controlled By:  ReplicaSet/pelias-placeholder-796f4588d9
Init Containers:
  placeholder-download:
    Container ID:  docker://e9e10c824520ff22d3e162632f631133da2973c8712fc5694dff02b322398876
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:cb63aa0641a885f54de20f61d152187419e8f6b159ed11a251a09d115fdff9bd
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      mkdir -p /data/placeholder/ &&
 wget -O- https://s3.amazonaws.com/geocodeearth-pelias-data/placeholder/store.sqlite3.gz | gunzip > /data/placeholder/store.sqlite3
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 10 Aug 2018 13:52:28 +0000
      Finished:     Fri, 10 Aug 2018 13:53:00 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1100m
      memory:  1Gi
    Requests:
      cpu:        200m
      memory:     512Mi
    Environment:  <none>
    Mounts:
      /data from data-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-87z4p (ro)
Containers:
  pelias-placeholder:
    Container ID:   docker://0a41b2c0251292555afa1edf2bab093cabddeae0e21730283526f6740b00f401
    Image:          pelias/placeholder:latest
    Image ID:       docker-pullable://pelias/placeholder@sha256:7f84171ccec3cc9f77b717a0e2047750832d45150a490af9926778f27cfbb77d
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Fri, 10 Aug 2018 10:06:16 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  512Mi
    Environment:
      PLACEHOLDER_DATA:  /data/placeholder/
      CPUS:              1
    Mounts:
      /data from data-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-87z4p (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  data-volume:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  default-token-87z4p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-87z4p
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason   Age               From                               Message
  ----    ------   ----              ----                               -------
  Normal  Pulling  38s (x9 over 3h)  kubelet, aks-agentpool-46734215-0  pulling image "busybox"
  Normal  Pulled   37s (x9 over 3h)  kubelet, aks-agentpool-46734215-0  Successfully pulled image "busybox"
  Normal  Created  37s (x9 over 3h)  kubelet, aks-agentpool-46734215-0  Created container
  Normal  Started  36s (x9 over 3h)  kubelet, aks-agentpool-46734215-0  Started container
```

**Comment by theobolo** [comment]
Seems to be a k8s problem, i can reproduce the issue with a simple deployment using a busybox as init-container. 

It's not Pelias related : https://github.com/kubernetes/kubernetes/issues/67261

**Comment by missinglink** [comment]
Excellent analysis, I wish we had more answers :(

Let's keep this issue open to track progress, even if the error isn't in our codebase.

**Comment by missinglink** [comment]
Am I correct in saying this is specific to Azure and doesn't affect Gcloud and AWS?

**Comment by orangejulius** [comment]
Yeah, thanks @theobolo for opening that issue. For the record, we've been running several interpolation pods for a few months on K8S v1.8.4 without seeing this particular issue

**Comment by JannikZed** [comment]
I really don't understand, why we don't let the user decide to use a persistent volume claim or not and the init container just checks, if the needed files are already downloaded or not. We have an upstart time of around 30 minutes right now and we also have fast gluster storage available for flexible persistent volumes .. But just replacing `emptyDir: {}` with a persistent volume claim is not working ..

**Comment by orangejulius** [comment]
@JannikZed "just" checking if data is there is not enough. At the very least, comparing against a checksum would be required to ensure the data is actually correct and up to date. I would love to see this implemented, although it should probably live in Pelias service repositories directly, rather than in the init-container.

I hope you agree that without validation of the data, merely using whatever happens to already be on disk is worse than re-downloading a known good copy of it from scratch.

As for deciding to use a PVC, that should be covered well by https://github.com/pelias/kubernetes/pull/44 which I would like to merge, but just haven't had time to get around to yet.

**Comment by orangejulius** [comment]
Looks like this Kubernetes issue was closed, and it seems solved, but it's unclear. I'm closing this issue since it was ultimately the same, but if anyone is looking to discuss additional interpolation download functionality, feel free to open a new issue in this repo or in https://github.com/pelias/interpolation/.
