### ISSUE TITLE
Helm template failed. Error: render error in "pelias/templates/api-deployment.tpl": template: pelias/templates/api-deployment.tpl:6:22: executing "pelias/templates/api-deployment.tpl" at <.Values.api.replicas>: can't evaluate field replicas in type interface {} : exit status 1

### ISSUE THREAD

**Issue by JannikZed** [pelias/kubernetes#59]
I'm having my problems installing pelias with helm. I only get this error message from helm:
`Helm template failed. Error: render error in "pelias/templates/api-deployment.tpl": template: pelias/templates/api-deployment.tpl:6:22: executing "pelias/templates/api-deployment.tpl" at <.Values.api.replicas>: can't evaluate field replicas in type interface {} : exit status 1`

Does anybody face the same issue? 

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by orangejulius** [comment]
Hi @JannikZed,
Thanks for the report. This _should_ be fixed in 0e9c524 which was just merged. If you can give it a test and confirm, please let me know if it worked for you.
