### ISSUE TITLE
unable to persist data

### ISSUE THREAD

**Issue by dataBikeHsUlm** [pelias/kubernetes#75]
> kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  annotations: pv.beta.kubernetes.io/gid: "1004"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/kubevolume"

> 

> kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

> 

In values.yaml I have the following:

> 

enabled: true
  replicas: 1
  host: "http://pelias-pip-service:3102/"
  dockerTag: "latest"
  maxUnavailable: 0 # adjusts rolling update settings
  retries: 1 # number of time the API will retry requests to the pip service
  timeout: 5000 # time in ms the API will wait for pip service responses
  annotations: {}
  pvc:
    create: true
    name: task-pv-claim
    storageClass: manual
    accessModes: ReadWriteMany
    storage: 10Gi
    annotations: {}

> 

helm install --name pelias --namespace pelias /data/git/pelias-kubernetes/kubernetes/ -f /data/git/pelias-kubernetes/kubernetes/values.yaml

And then I get the following error in my kubernetes dashboard:
"pod has unbound immediate PersistentVolumeClaims"

What am I missing?

**Comment by arne-cl** [comment]
Hi @dataBikeHsUlm,
how did you solve your persistence issues?
