### ISSUE TITLE
Which data is shared between pelias services?

### ISSUE THREAD

**Issue by arne-cl** [pelias/kubernetes#78]
I have trouble getting the helm installation of pelias running (the docker-compose version works fine). I don't understand if all the services accessing the `/data` mountPath expect to access the
same PV / share data between each other.

In the `values.yaml`, the services `interpolation` and `pip` are the only ones with a PVC.
Both PVCs are suggested to be used with `accessModes: ReadWriteMany`.
Since the suggested names of the PVCs are different (`interpolation-pvc` vs. `pip-pvc`), I would
assume that they access different PVs (i.e. `interpolation` and `pip` don't share data).

If this is true, then `accessModes: ReadWriteOnce` would be sufficient here.

When running `helm template` I noticed that the `placeholder` service is accessing
a VolumeMount named `data-volume` with mountPath `/data` (just like `interpolation` and `pip` do),
but `values.yaml` does not suggest a PVC for the `placeholder` service. In this case,
`helm` generates this, which is probably wrong:

```
      volumes:
        - name: data-volume
          emptyDir: {}
```

**Comment by orangejulius** [comment]
Hi @arne-cl,

You're right that interpolation and pip don't share data. I think the idea behind those comments was that multiple instances of the interpolation or pip service could share an underlying PV. 

Personally I haven't used anything but `emptyDir`s with Pelias services, and have been completely happy to pay for the reduced possibility of issues with, for example, partially downloaded data, out of date data, conflicts between replicas, etc with slightly higher pod startup times.

If you find anything that works well for you, let us know.

**Comment by arne-cl** [comment]
Hi @orangejulius,

thanks for the clarification! I will try `emptyDir` for all `data-volume` VolumeMounts for testing and will let you know once I've figured out more about PVCs in this context.
