### ISSUE TITLE
polylines-import: road_network.gz not available in S3 bucket

### ISSUE THREAD

**Issue by arne-cl** [pelias/kubernetes#83]
The initContainer of the `polylines-import` job crashes:

```
$ kubectl-1.8.15 -n geocoding-staging logs polylines-import-3fmjl -c download
Connecting to s3.us-east-2.amazonaws.com (52.219.88.186:443)
wget: note: TLS certificate validation not implemented
-                   gunzip: invalid magic
 100% |********************************|   449  0:00:00 ETA
```

The underlying error is a ` Redirection (301) without location`. If you GET that url
in your browser, you'll get this tip:

```
<Error>
  <Code>PermanentRedirect</Code>
  <Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message>
  <Endpoint>s3.amazonaws.com</Endpoint>
  <Bucket>pelias-data.nextzen.org</Bucket>
  <RequestId>7698B1C7B9F041B6</RequestId>
  ...
</Error>
```

Unfortunately, `https://s3.amazonaws.com/pelias-data.nextzen.org/poylines/road_network.gz` does also not exist.

**Comment by missinglink** [comment]
Hi @arne-cl,

You can find a more up-to-date version of that file at https://geocode.earth/data
The `road_network.gz` file is a much older version of the same file which I produced years ago and is now out-of-date.

If you'd like the older file it's still available, but there is a typo in that url `poylines` vs `polylines`.
```
curl --head https://s3.amazonaws.com/pelias-data.nextzen.org/polylines/road_network.gz
```

Do you know where this link address is coming from? I'd like to fix it.

**Comment by missinglink** [comment]
Fixed via https://github.com/pelias/kubernetes/commit/e15e09e7e62aa4b482ed52245ef9fc9507e2898e
I'd still recommend using the newer data :)

**Comment by arne-cl** [comment]
Dear @missinglink,
thank you for the speedy fix!

For clarification: since you recommend using the newer file from geocode.earth, why did choose to fix the link to the old data instead of replacing it with a link to the newer version?

**Comment by missinglink** [comment]
We're still deciding on how best to handle the data downloads on our site, I just hosted that one file for now as it's been requested by other users.

In order to avoid more broken links in the future I think it's best that people visit the download page and manually get the most recent link until we have a more robust solution in place.

**Comment by missinglink** [comment]
There is also a financial cost with hosting large files.
It's not really a big deal for a few downloads, but once these large links are hard-coded in configs then the S3 costs alone can easily spiral to be hundreds of USD per month.

The old data is hosted in the nextzen bucket, which is funded by grants from AWS, that funding was provided so we could provide an uninterrupted service when Mapzen shut down.
