### ISSUE TITLE
planet download path for Interpolation databases.

### ISSUE THREAD

**Issue by Mokto** [pelias/kubernetes#97]
Should replace `https://s3.amazonaws.com/pelias-data.nextzen.org/portland-metro/interpolation`

Thanks!

**Comment by orangejulius** [comment]
Hi @Mokto,
Unfortunately as mentioned in https://github.com/pelias/kubernetes/pull/93 the full planet interpolation download won't be available any longer.

The files were almost 20GB compressed, and being hosted using the same sponsorship as all the other post-Mapzen project creidits (such as who's on first, nextzen, etc).

While overall the usage was moderate, there were a few IP addresses downloading the files hundreds of times, and so the bandwidth costs were actually quite high.

For now, you'll have to build and host the interpolation database yourself. It is pretty hard, we'd love help making it easier and faster.

In the future we're looking at offering download options through [geocode.earth](https://geocode.earth). The details are still TBD, but for up to date full planet builds there would certainly be a charge.
