### ISSUE TITLE
How do I access the pelias api running on kubernetes?

### ISSUE THREAD

**Issue by pravink** [pelias/kubernetes#98]
I have managed to deploy the pelias api on kubernetes cluster but not able to access it via kubernetes master.

i can able to access it directly using the node -[specific port exposed externally.]

Thanks,
Pravin!

**Comment by orangejulius** [comment]
Hi @pravink,
Thanks for writing in.

We intentionally don't do much work regarding exposing the API in this chart, since usually everyone seems to want something very specific for their situation. I'm curious why you want access from the kubernetes masters specifically?

**Comment by pravink** [comment]
Thanks for your response. 

There is no specific intention to use master node for accessing application endpoints deployed on pods. I initially thought all applications deployed on kubernetes has to be accessed through load balancer of master node. as re-deploying pelias configuration on cluster using helm can be achieved using helm upgrade. so I am good right now to redeploy changes to pelias config using the helm upgrade and accessing the same using external load balancer deployed on the node itself.

Thanks!
